language: ruby
cache: bundler
script: bundle exec rake release_checks
before_install:
- gem update bundler
matrix:
  fast_finish: true
  include:
  - rvm: 2.5.0
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04
    script: bundle exec rake beaker
    services: docker
    sudo: required
notifications:
  email: false
