language: ruby
cache: 
  bundler: true
  directories:
    - vendor/bundle
    - .tmp/librarian/cache
before_install:
#- gem install rubygems-update
#- gem update --system
#- gem update bundler
- gem install bundler -v '2.1.4'
- bundle --version
#- rm -f Gemfile.lock
matrix:
  fast_finish: true
  include:
  - rvm: 2.5.8
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 5.0"
branches:
  only:
  - master
script:
  # Test case:
  # 1. rspec (unit test)
  # 2. puppet-lint (coding style test)
  - "bundle exec rake release_checks"
  # 3. beaker (acceptance test)
  - "bundle exec librarian-puppet install"
